wandb_version: 1

BASE_LR:
  desc: null
  value: 0.0001
BATCH_SIZE_PER_IMAGE:
  desc: null
  value: 32
EVAL_PERIOD:
  desc: null
  value: 500
IMS_PER_BATCH:
  desc: null
  value: 1
MAX_ITER:
  desc: null
  value: 500
MODEL:
  desc: null
  value: COCO-Detection/faster_rcnn_R_101_C4_3x.yaml
NAME:
  desc: null
  value: '{''BASE_LR'': 0.0001, ''BATCH_SIZE_PER_IMAGE'': 32, ''IMS_PER_BATCH'': 1,
    ''MODEL'': ''faster_rcnn_R_101_C4_3x.yaml''}'
SCORE_THRESH_TEST:
  desc: null
  value: 0.625
_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    code_path: code/V2/run.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1635656704
    t:
      1:
      - 1
      - 3
      - 5
      2:
      - 1
      - 3
      - 5
      3:
      - 2
      - 13
      - 16
      4: 3.8.12
      5: 0.12.4
      8:
      - 5
