wandb_version: 1

BASE_LR:
  desc: null
  value: 0.1
BATCH_SIZE_PER_IMAGE:
  desc: null
  value: 8
EVAL_PERIOD:
  desc: null
  value: 125
IMS_PER_BATCH:
  desc: null
  value: 1
MAX_ITER:
  desc: null
  value: 125
MODEL:
  desc: null
  value: COCO-Detection/faster_rcnn_R_50_C4_1x.yaml
NAME:
  desc: null
  value: '{''BASE_LR'': 0.1, ''BATCH_SIZE_PER_IMAGE'': 8, ''CREATE_TARGET_AND_PREDS'':
    55, ''EVAL_PERIOD'': 125, ''IMS_PER_BATCH'': 1, ''LABELS'': [''Card''], ''MAX_ITER'':
    125, ''MODEL'': ''faster_rcnn_R_50_C4_1x.yaml'', ''SCORE_THRESH_TEST'': 0.625}'
SCORE_THRESH_TEST:
  desc: null
  value: 0.625
_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    code_path: code/V2/run.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1635515839
    t:
      1:
      - 1
      - 5
      3:
      - 13
      - 16
      4: 3.8.12
      5: 0.12.4
      8:
      - 5
