wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.3
    code_path: code/V2/run.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1637332948
    t:
      1:
      - 1
      - 3
      - 5
      3:
      - 13
      4: 3.8.12
      5: 0.12.3
      8:
      - 5
