wandb_version: 1

BASE_LR:
  desc: null
  value: 0.00025
BATCH_SIZE_PER_IMAGE:
  desc: null
  value: 128
EVAL_PERIOD:
  desc: null
  value: 500
IMS_PER_BATCH:
  desc: null
  value: 2
MAX_ITER:
  desc: null
  value: 500
MODEL:
  desc: null
  value: COCO-Detection/faster_rcnn_R_50_C4_3x.yaml
NAME:
  desc: null
  value: faster_rcnn_R_50_C4_3x.yaml
SCORE_THRESH_TEST:
  desc: null
  value: 0.625
_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    code_path: code/V2/run.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1635516564
    t:
      1:
      - 1
      - 3
      - 5
      3:
      - 13
      - 16
      4: 3.8.12
      5: 0.12.4
      8:
      - 5
