wandb_version: 1

BASE_LR:
  desc: null
  value: 0.00025
BATCH_SIZE_PER_IMAGE:
  desc: null
  value: 128
EVAL_PERIOD:
  desc: null
  value: 5
IMS_PER_BATCH:
  desc: null
  value: 2
MAX_ITER:
  desc: null
  value: 50
MODEL:
  desc: null
  value: COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml
NAME:
  desc: null
  value: baseline
SCORE_THRESH_TEST:
  desc: null
  value: 0.625
_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    code_path: code/V2/Final.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1635446001
    t:
      1:
      - 1
      2:
      - 1
      - 3
      3:
      - 13
      - 16
      4: 3.8.12
      5: 0.12.4
      8:
      - 5
